services:
  db:
    image: postgres:16
    container_name: local_pgdb_ecf1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_ecf1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata_ecf1:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    networks:
      - db_network_ecf1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_ecf1"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin_gui_ecf1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - local_pgadmin_ecf1:/var/lib/pgadmin
    networks:
      - db_network_ecf1

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline_ecf1
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DB_NAME: db_ecf1
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: images
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./sql:/app/sql:ro
    networks:
      - db_network_ecf1
    command: ["python", "-m", "src.main"]

  minio:
    image: minio/minio:latest
    container_name: minio_ecf1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    volumes:
      - local_minio_data_ecf1:/data
    networks:
      - db_network_ecf1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 20


volumes:
  local_pgdata_ecf1:
  local_pgadmin_ecf1:
  local_minio_data_ecf1:


networks:
  db_network_ecf1: {}
